name: Deny Check

on: [push, pull_request]

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 最新のstable Rustをインストール
      - uses: dtolnay/rust-toolchain@stable

      - uses: EmbarkStudios/cargo-deny-action@v2
