name: ライセンスチェック

on: [push, pull_request, workflow_dispatch]

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: ライセンスのチェック
        uses: EmbarkStudios/cargo-deny-action@v2
